//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ring()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int RingID { get; set; }
        public string Brand { get; set; }
        public string Material { get; set; }
        public string JewelryType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Collection { get; set; }
        public Nullable<int> GoldCarat { get; set; }
        public string GemType { get; set; }
        public string Gender { get; set; }
        public string MaterialColor { get; set; }
        public string ImagePro { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
